### ISSUE TITLE
Error while building the project

### ISSUE THREAD

**Issue by dareenkf** [mistupv/JavaSlicer#42]
Hi, I tried to run the project, but unfortunately I got this error.
`[ERROR] Failed to execute goal on project sdg-cli: Could not resolve dependencies for project es.upv.mist.slicing:sdg-cli:jar:1.2.4: Failed to collect dependencies at es.upv.mist.slicing:sdg-core:jar:1.2.4: Failed to read artifact descriptor for es.upv.mist.slicing:sdg-core:jar:1.2.4: Failure to find es.upv.mist.slicing:sdg:pom:1.2.4 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1] `

I checked the ~/.m2/repository/es/upv/mist/slicing/sdg-core/1.2.4/ , and I found both (sdg-core-1.2.4.jar & sdg-core-1.2.4.pom ). 
Do you have an idea why I got this error?

**Comment by cargaji** [comment]
Hi there! Weirdly, I get the same error on Linux, but it didn't appear on macOS under the same `mvn` version.

I think the correct solution is to call `mvn package` from the root of the repository, instead of individually compiling each module. This takes care of the dependencies automatically and you can find `sdg-cli-{version}-with-dependencies.jar` in `sdg-cli/target/`. The more specific command would be `mvn package -pl sdg-cli -am`, but `mvn package` works (though it packages both modules). I've tried it in Ubuntu (Maven 3.6.3), so it should work for you too.

I really don't understand how Maven can't find the dependency in the local repo, if you ever find out why, I'd be interested to know.
